manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/CrossR
  projects:
    - name: zmk
      remote: CrossR/RowOffset 
      revision: main
      import: app/west.yml
  self:
    path: config
